### ISSUE TITLE
Subtlety

### ISSUE THREAD

**Issue by davecastlevania** [Wynterblayde/prj-rev-bwfs-dasmoto#1]
https://github.com/Wynterblayde/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L6

https://github.com/Wynterblayde/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L10

Use this for ampersands 

`&amp;`

**Comment by Wynterblayde** [comment]
Thank you.
